To calculate FST, I need to use unfolded SAF and SFS using the reference to polarize the alleles. I need a saf file for each population. first make filelists for each pop:


In [ ]:
 find . -name "*_pairedplus_marked_dupes.bam" -exec cp -i {} ../allBam/ \; 

In [ ]:
sed 's/$/_pairedplus_marked_dupes.bam/g' /local/home/sarahgw/WGS/Sequences/NJ_E/NJ_E_list>NJ_E_filelist

Calculate unfolded SAF for each population, see https://github.com/ANGSD/angsd/issues/65 for justification of folded vs unfolded

In [ ]:
for POP in NJ_E NJ_U NY_E NY_U VT_E VT_U; do echo $POP; ~/angsd/angsd -P 10 -b /local/home/sarahgw/WGS/Sequences/filelists/"$POP".filelist -anc /local/home/sarahgw/references/Myotis_Lucifugus2.0/Myotis_lucifugus.Myoluc2.0.dna_sm.toplevel.fa -GL 1 -dosaf 1 -minMapQ 30 -minQ 20 -out /local/home/sarahgw/WGS/SNPS/All_mylu/"$POP"_un; done

redo NJ_U for just the "dead" samples

In [ ]:
~/angsd/angsd -P 30 -b /local/home/sarahgw/WGS/Sequences/filelists/NJ_U_D.filelist -anc /local/home/sarahgw/references/Myotis_Lucifugus2.0/Myotis_lucifugus.Myoluc2.0.dna_sm.toplevel.fa -GL 1 -dosaf 1 -minMapQ 30 -minQ 20 -out /local/home/sarahgw/WGS/SNPS/All_mylu/NJ_U_D_un  

redo NJ_U and VT_U after removing septentrionalis samples

In [ ]:
~/angsd/angsd -P 30 -b /local/home/sarahgw/WGS/Sequences/filelists/NJ_U.filelist -anc /local/home/sarahgw/references/Myotis_Lucifugus2.0/Myotis_lucifugus.Myoluc2.0.dna_sm.toplevel.fa -GL 1 -dosaf 1 -minMapQ 30 -minQ 20 -out /local/home/sarahgw/WGS/SNPS/All_mylu/NJ_U_un  

In [ ]:
~/angsd/angsd -P 30 -b /local/home/sarahgw/WGS/Sequences/filelists/VT_U.filelist -anc /local/home/sarahgw/references/Myotis_Lucifugus2.0/Myotis_lucifugus.Myoluc2.0.dna_sm.toplevel.fa -GL 1 -dosaf 1 -minMapQ 30 -minQ 20 -out /local/home/sarahgw/WGS/SNPS/All_mylu/VT_U_un  

Calculate 2d sfs for each pair 

need to limit to 1 billion sites, then take sum of each column

In [ ]:
~/angsd/angsd/misc/realSFS -P 30 ~/WGS/saf/NJ_E_un.saf.idx ~/WGS/saf/NJ_U_un.saf.idx -nSites 1000000000 > ~/WGS/sfs/NJ_EU_unfull

In [ ]:
awk 'BEGIN{FS=OFS=" "}
     NR>=1{for (i=1;i<=NF;i++) a[i]+=$i}
     END{for (i=1;i<=NF;i++) printf a[i] OFS; printf "\n"}' ~/WGS/sfs/NJ_EU_unfull.ml > ~/WGS/sfs/NJ_EU_unfull_sum.ml
        o=open('~/WGS/sfs/NJ_EU_unfullnorm.ml', 'w')

In [4]:
!tail -n 1 /local/home/sarahgw/WGS/SNPS/All_mylu/sfs/NJ_EU_unfull

642070890.488778 24679234.027051 0.000596 0.004285 0.000433 2428651.971257 24.136881 0.000000 0.000291 0.000022 0.000017 0.000077 0.000204 0.000502 0.000653 0.000394 0.000000 0.000000 0.000000 0.000072 0.000027 0.000139 0.000077 0.000016 0.000007 0.000002 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.124948 14.214494 1.581951 0.203526 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 12633560.078426 16.569237 0.001693 6117685.924676 17307.864781 101.633637 0.827917 1.915163 4.673731 1.186210 0.402718 2.907272 5.693647 13.872329 5.743290 12.202514 4.215832 0.066373 1.856319 0.160557 0.049813 0.049468 0.001551 0.004573 0.001893 0.000091 0.000077 0.000012 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 1920.389590 0.006303 6605689.233404 9832.899063 127.277892 41.752925 198.223470 96.505521 3193.134746 4591.186487 9041.048569 3285.446162 5778.00

In [5]:
import numpy as np
e=np.loadtxt('/local/home/sarahgw/WGS/SNPS/All_mylu/sfs/NJ_EU_unfull')
e/e.sum(axis=1, keepdims=True)

In [6]:
e

array([[  9.13825946e+08,   5.09971152e+06,   2.15903683e+07, ...,
          8.70000000e-05,   2.32248256e+05,   4.41481814e+05],
       [  6.42070890e+08,   2.46792340e+07,   5.96000000e-04, ...,
          3.10165462e+04,   1.23356896e+05,   3.67091521e+05]])

In [9]:
f=e/e.sum(axis=1, keepdims=True)

In [12]:
f.sum(axis=1, keepdims=True)

array([[ 1.],
       [ 1.]])

In [13]:
f

array([[  9.13825946e-01,   5.09971152e-03,   2.15903683e-02, ...,
          8.70000000e-14,   2.32248256e-04,   4.41481814e-04],
       [  8.94205217e-01,   3.43705035e-02,   8.30042784e-13, ...,
          4.31964100e-05,   1.71797822e-04,   5.11244410e-04]])

In [15]:
np.savetxt('/local/home/sarahgw/WGS/SNPS/All_mylu/sfs/NJ_EU_unfull_norm', f, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ')

In [ ]:
~/angsd/angsd/misc/realSFS -P 10 ~/WGS/saf/NY_E_un.saf.idx ~/WGS/saf/NY_U_un.saf.idx -nSites 1000000000 > ~/WGS/sfs/NY_EU_unfull

In [ ]:
awk 'BEGIN{FS=OFS=" "}
     NR>=1{for (i=1;i<=NF;i++) a[i]+=$i}
     END{for (i=1;i<=NF;i++) printf a[i] OFS; printf "\n"}' ~/WGS/sfs/NY_EU_unfull.ml > ~/WGS/sfs/NY_EU_unfull_sum.ml

In [ ]:
~/angsd/misc/realSFS -P 30 ~/WGS/SNPS/All_mylu/saf/VT_E_un.saf.idx ~/WGS/SNPS/All_mylu/saf/VT_U_un.saf.idx -nSites 100000000 > ~/WGS/SNPS/All_mylu/sfs/VT_EU_unfullnose.ml; echo "NY FST Done" | mailx gw.sarah@gmail.com

In [ ]:
awk 'BEGIN{FS=OFS=" "}
     NR>=1{for (i=1;i<=NF;i++) a[i]+=$i}
     END{for (i=1;i<=NF;i++) printf a[i] OFS; printf "\n"}' ~/WGS/sfs/VT_EU_unfull.ml > ~/WGS/sfs/VT_EU_unfull_sum.ml

In [ ]:
#~/angsd/angsd/misc/realSFS -P 30 ~/WGS/saf/NJ_U_D_un.saf.idx ~/WGS/saf/NJ_E_un.saf.idx -nSites 1000000000 > ~/WGS/sfs/NJ_EUD_unfull

In [ ]:
awk 'BEGIN{FS=OFS=" "}
     NR>=1{for (i=1;i<=NF;i++) a[i]+=$i}
     END{for (i=1;i<=NF;i++) printf a[i] OFS; printf "\n"}' ~/WGS/sfs/NJ_EUD_unfull > ~/WGS/sfs/NJ_EUD_unfull_sum.ml

In [ ]:
~/angsd/angsd/misc/realSFS -P 10 ~/WGS/saf/NJ_U_un.saf.idx ~/WGS/saf/NY_U_un.saf.idx -nSites 1000000000 > ~/WGS/sfs/NJNY_U_unfull

In [ ]:
awk 'BEGIN{FS=OFS=" "}
     NR>=1{for (i=1;i<=NF;i++) a[i]+=$i}
     END{for (i=1;i<=NF;i++) printf a[i] OFS; printf "\n"}' ~/WGS/SNPS/All_mylu/sfs/NJNY_U_unfull > ~/WGS/SNPS/All_mylu/sfs/NJNY_U_unfull_sum.ml

In [ ]:
~/angsd/angsd/misc/realSFS -P 30 ~/WGS/saf/VT_U_un.saf.idx ~/WGS/saf/NY_U_un.saf.idx -nSites 1000000000 > ~/WGS/sfs/VTNY_U_unfull

In [ ]:
awk 'BEGIN{FS=OFS=" "}
     NR>=1{for (i=1;i<=NF;i++) a[i]+=$i}
     END{for (i=1;i<=NF;i++) printf a[i] OFS; printf "\n"}' ~/WGS/SNPS/All_mylu/sfs/VTNY_U_unfull > ~/WGS/SNPS/All_mylu/sfs/VTNY_U_unfull_sum.ml

In [ ]:
~/angsd/angsd/misc/realSFS -P 30 ~/WGS/saf/NJ_U_un.saf.idx ~/WGS/saf/VT_U_un.saf.idx -nSites 1000000000 > ~/WGS/sfs/NJVT_U_unfull

In [ ]:
awk 'BEGIN{FS=OFS=" "}
     NR>=1{for (i=1;i<=NF;i++) a[i]+=$i}
     END{for (i=1;i<=NF;i++) printf a[i] OFS; printf "\n"}' ~/WGS/SNPS/All_mylu/sfs/NJVT_U_unfull > ~/WGS/SNPS/All_mylu/sfs/NJVT_U_unfull_sum.ml

In [ ]:
~/angsd/angsd/misc/realSFS -P 30 ~/WGS/saf/NJ_E_un.saf.idx ~/WGS/saf/NY_E_un.saf.idx -nSites 1000000000 > ~/WGS/sfs/NJNY_E_unfull

In [ ]:
awk 'BEGIN{FS=OFS=" "}
     NR>=1{for (i=1;i<=NF;i++) a[i]+=$i}
     END{for (i=1;i<=NF;i++) printf a[i] OFS; printf "\n"}' ~/WGS/SNPS/All_mylu/sfs/NJNY_E_unfull > ~/WGS/SNPS/All_mylu/sfs/NJNY_E_unfull_sum.ml

In [ ]:
~/angsd/angsd/misc/realSFS -P 10 ~/WGS/saf/VT_E_un.saf.idx ~/WGS/saf/NY_E_un.saf.idx -nSites 1000000000 > ~/WGS/sfs/VTNY_E_unfull

In [ ]:
awk 'BEGIN{FS=OFS=" "}
     NR>=1{for (i=1;i<=NF;i++) a[i]+=$i}
     END{for (i=1;i<=NF;i++) printf a[i] OFS; printf "\n"}' ~/WGS/sfs/VTNY_E_unfull > ~/WGS/sfs/VTNY_E_unfull_sum.ml

In [ ]:
~/angsd/angsd/misc/realSFS -P 30 ~/WGS/saf/NJ_E_un.saf.idx ~/WGS/saf/VT_E_un.saf.idx -nSites 1000000000 > ~/WGS/sfs/NJVT_E_unfull

In [ ]:
awk 'BEGIN{FS=OFS=" "}
     NR>=1{for (i=1;i<=NF;i++) a[i]+=$i}
     END{for (i=1;i<=NF;i++) printf a[i] OFS; printf "\n"}' ~/WGS/sfs/NJVT_E_unfull > ~/WGS/sfs/NJVT_E_unfull_sum.ml

Calculate FST for each pair

NY Exposed vs Unexposed:

In [ ]:
~/angsd/misc/realSFS fst index ~/WGS/SNPS/All_mylu/saf/NY_E_un.saf.idx ~/WGS/SNPS/All_mylu/saf/NY_U_un.saf.idx -sfs ~/WGS/SNPS/All_mylu/sfs/NY_EU_unfull_sum.ml -fstout NY_EU_untest

In [ ]:
~/angsd/angsd/misc/realSFS fst stats NY_EU_un.fst.idx

Fst.Weight:0.016618

In [ ]:
~/angsd/angsd/misc/realSFS fst stats2  NY_EU_un.fst.idx -win 10000 -step 2000 -type 1 > NY_EU_un.fst.sw

NJ Exposed vs Unexposed

In [ ]:
~/angsd/misc/realSFS fst index /local/home/sarahgw/WGS/SNPS/All_mylu/saf/NJ_E_un.saf.idx ~/WGS/SNPS/All_mylu/saf/NJ_U_un.saf.idx -sfs ~/WGS/SNPS/All_mylu/sfs/NJ_EU_unfull_sum.ml -fstout NJ_EU_un_test

In [ ]:
~/angsd/angsd/misc/realSFS fst stats NJ_EU_un.fst.idx

FST.Unweight[nObs:1718436087]:0.018535 Fst.Weight:0.018241

In [ ]:
~/angsd/angsd/misc/realSFS fst stats2  NJ_EU_un.fst.idx -win 10000 -step 2000 -type 1 > NJ_EU_un.fst.sw

NJ Exposed vs Unexposed Dead

In [ ]:
~/angsd/angsd/misc/realSFS fst index ~/WGS/saf/NJ_E_un.saf.idx ~/WGS/saf/NJ_U_D_un.saf.idx -sfs ~/WGS/sfs/NJ_EUD_unfull_sum.ml -fstout NJ_EUD_un

In [ ]:
~/angsd/angsd/misc/realSFS fst stats NJ_EUD_un.fst.idx

In [ ]:
~/angsd/angsd/misc/realSFS fst stats2  NJ_EUD_un.fst.idx -win 10000 -step 2000 -type 1 > NJ_EUD_un.fst.sw

VT Exposed vs Unexposed 

In [ ]:
~/angsd/misc/realSFS fst index ~/WGS/SNPS/All_mylu/saf/VT_E_un.saf.idx ~/WGS/SNPS/All_mylu/saf/VT_U_un.saf.idx -sfs ~/WGS/SNPS/All_mylu/sfs/VT_EU_unfull_sum.ml -fstout VT_EU_untest

In [ ]:
~/angsd/angsd/misc/realSFS fst stats2  VT_EU_un.fst.idx -win 10000 -step 2000 -type 1 > NJ_EU_un.fst.sw

In [ ]:
~/angsd/angsd/misc/realSFS fst stats VT_EU_un.fst.idx

FST.Unweight[nObs:1734759399]:0.013436 Fst.Weight:0.014751

Calculate Three way fsts

Unexposed:

In [ ]:
~/angsd/misc/realSFS fst index ~/WGS/SNPS/All_mylu/saf/NY_U_un.saf.idx ~/WGS/SNPS/All_mylu/saf/NJ_U_un.saf.idx ~/WGS/SNPS/All_mylu/saf/VT_U_un.saf.idx -sfs ~/WGS/SNPS/All_mylu/sfs/NJNY_U_unfull_sum.ml -sfs ~/WGS/SNPS/All_mylu/sfs/VTNY_U_unfull_sum.ml -sfs ~/WGS/SNPS/All_mylu/sfs/NJVT_U_unfull_sum.ml -fstout ~/WGS/SNPS/All_mylu/fst/NJNYVT_U_un

In [ ]:
#~/angsd/angsd/misc/realSFS fst stats ~/WGS/sfs/NJNYVT_U_un.fst.idx

Exposed

In [ ]:
~/angsd/angsd/misc/realSFS fst index ~/WGS/saf/NY_E_un.saf.idx ~/WGS/saf/NJ_E_un.saf.idx ~/WGS/saf/VT_E_un.saf.idx -sfs ~/WGS/sfs/NJNY_E_unfull_sum.ml -sfs ~/WGS/sfs/VTNY_E_unfull_sum.ml -sfs ~/WGS/sfs/NJVT_E_unfull_sum.ml -fstout NJNYVT_E_un

In [ ]:
~/angsd/angsd/misc/realSFS fst stats ~/WGS/sfs/NJNYVT_E_un.fst.idx

       -> FST.Unweight[nObs:1694040644]:0.027544 Fst.Weight:0.137775 
        -> FST.Unweight[nObs:1694040644]:0.043776 Fst.Weight:0.140448 
        -> FST.Unweight[nObs:1694040644]:0.011623 Fst.Weight:0.014038 
        -> pbs.pop1     0.142723
        -> pbs.pop2     0.005516
        -> pbs.pop3     0.008622

In [ ]:
~/angsd/misc/realSFS fst print NJ_EU_unfull.fst.idx> NJ_EU_full_fst

In [ ]:
awk -F, 'FNR==NR {a[$1]=$0; next}; $1 in a {print a[$1]}' NJ_EU_full_FST NJ_SNP_sites1_sorted.txt

In [ ]:
~/angsd/misc/realSFS fst print VT_EU_full.fst.idx  > VT_EU_full_SNP_freq

In [ ]:
awk 'FNR==NR {a[$1$2]=$0; next}; $1$2 in a {print a[$1$2]}' VT_EU_full_SNP_freq VT_SNP_sites1_sorted.txt> VT_EU_full_SNP_fst

In [ ]:
~/angsd/misc/realSFS fst print NJ_EU_full.fst.idx > NJ_EU_full_SNP_freq

This seems to be arbitrarily filtering, the number of lines doesnt match and there are definitely sites in the output that aren't in the SNPs file, try again with a sorted SNP file? did't work. use awk to fiter by snps

In [ ]:
~/angsd/misc/realSFS fst print NJ_EU_full.fst.idx -sites NJ_SNP_sites1_sorted.txt > NJ_EU_full_SNP_freq1

In [ ]:
~/angsd/misc/realSFS fst print NY_EU_unfull.fst.idx -sites NY_SNP_sites1.txt > NY_EU_unfull_SNP_freq

In [ ]:
~/angsd/misc/realSFS fst print NY_EU_unfull.fst.idx> NJ_EU_unfull_fst

In [ ]:
~/angsd/misc/realSFS fst print VT_EU_full.fst.idx> VT_EU_full_fst

In [ ]:
grep 'AAPE02072785' NJ_EU_full_fst > NJ_AAPE02072785

This doesnt make much sense: mt change in allele freq: -0.0103409
full change in allele freq: -0.0153759

In [ ]:
awk '$4>0.40' /local/home/sarahgw/WGS/SNPS/All_mylu/NJ_EU_full.fst.gz

Calculate FST for NY

Started at 1:15 PM on 7/11/17 on annotate

In [ ]:
~/angsd/angsd/misc/realSFS fst index NY_E_un.saf.idx NY_U_un.saf.idx -sfs NY_EU_unfull.ml -fstout NY_EU_unfull; echo "NY FST Done" | mailx gw.sarah@gmail.com

In [ ]:
~/angsd/angsd/misc/realSFS fst stats NY_EU_unfull.fst.idx 

This is the unfolded FST values: -> FST.Unweight[nObs:1710526195]:0.031527 Fst.Weight:0.051177
This is the folded FST values:-> FST.Unweight[nObs:1710526195]:0.030941 Fst.Weight:0.050585

In [ ]:
~/angsd/misc/realSFS fst stats2 NY_EU_unfull.fst.idx -win 10000 -step 2000 -type 1 > NY_unfull_sw2

Calculate FST for VT

In [ ]:
~/angsd/angsd/misc/realSFS fst index VT_E.saf.idx VT_U.saf.idx -sfs VT_EU_full.ml -fstout VT_EU_full ; echo "VT FST Done"| mailx gw.sarah@gmail.com 

In [ ]:
~/angsd/angsd/misc/realSFS fst stats VT_EU_full.fst.idx 

-> FST.Unweight[nObs:1734759399]:0.029444 Fst.Weight:0.045089

In [ ]:
~/angsd/misc/realSFS fst stats2 VT_EU_full.fst.idx -win 10000 -step 2000 -type 1 > VT_full_sw2

In [ ]:
awk '$5>0.10' /local/home/sarahgw/WGS/SNPS/All_mylu/VT_sw 

Get sequences for AAPE02072785

In [ ]:
grep 'AAPE02072785' -A 300 /local/home/sarahgw/references/Myotis_Lucifugus2.0/Myotis_lucifugus.Myoluc2.0.dna_sm.toplevel.fa | tr -d "\n\r" | cut -c 7000-15000 >/local/home/sarahgw/WGS/SNPS/All_mylu/AAPE02072785

In [ ]:
52357001 52365001

In [ ]:
grep 'GL429767' -A 300000 /local/home/sarahgw/references/Myotis_Lucifugus2.0/Myotis_lucifugus.Myoluc2.0.dna_sm.toplevel.fa | tr -d "\n\r" | cut -c 52357001-52365001 >/local/home/sarahgw/WGS/SNPS/All_mylu/GL429767

Test for why GL429767 is no longer an FST outlier? 
Can I pull out the allele frequencies and rerun FST analysis with new allele freqs but only subset of samples?
Can I look to see if genotype likelihoods or allele frquencies change in this region with full dataset?
Can I test if the change is on the part of the Exposed or Unexposed populations?--first, try doing fst with saf of old nj exposed and new nj unexposed.  

In [ ]:
~/angsd/angsd/misc/realSFS -P 15 angsdout_SAF_pairedplus_filt_E.saf.idx NJ_U.saf.idx > NJ_EU_sub.ml

In [ ]:
~/angsd/angsd/misc/realSFS fst index angsdout_SAF_pairedplus_filt_E.saf.idx NJ_U.saf.idx -sfs NJ_EU_sub.ml -fstout NJ_EU_sub

In [ ]:
~/angsd/angsd/misc/realSFS fst stats NJ_EU_sub.fst.idx 

FST.Unweight[nObs:1622446386]:0.046976 Fst.Weight:0.080651
Okay, so it seems like its not the exposed that are making a difference its the unexposed?

In [ ]:
~/angsd/angsd/misc/realSFS fst stats2 NJ_EU_sub.fst.idx -win 10000 -step 2000 -type 1 >  NJ_EU_sub_sw2