In [8]:
require(ACER)
require(data.table)
require(poolSeq)

In [9]:
setwd("/data/sarahgw/WGS/SNPS/All_mylu/")


In [10]:
nje=fread("mafs/NJ_E_filt1.mafs", header=FALSE)
nju=fread("mafs/NJ_U_filt1.mafs", header=FALSE)
nye=fread("mafs/NY_E_filt1.mafs", header=FALSE)
nyout=fread("mafs/NY_U_noOut_filt.mafs")

Read 44829666 rows and 8 (of 8) columns from 2.119 GB file in 00:00:40
Read 44829666 rows and 8 (of 8) columns from 2.108 GB file in 00:00:42
Read 44829666 rows and 8 (of 8) columns from 2.112 GB file in 00:00:38
Read 44829616 rows and 8 (of 8) columns from 2.113 GB file in 00:00:42


In [13]:
colnames(nje)=c("Scaffold", "Position", "Major", "Minor", "Maf1_E", "Maf2_NJE", "Maf3_E", "nInd_NJE")
colnames(nju)=c("Scaffold", "Position", "Major", "Minor", "Maf1_U", "Maf2_NJU", "Maf3_U", "nInd_NJU")
colnames(nye)=c("Scaffold", "Position", "Major", "Minor", "Maf1_E", "Maf2_NYE", "Maf3_E", "nInd_NYE")
colnames(nyout)=c("Scaffold", "Position", "Major", "Minor", "Maf1_E", "Maf2_NYU", "Maf3_E", "nInd_NYU")

In [19]:
nrow(nje)
nrow(nju)
nrow(nye)
nrow(nyout)

[1] 44829666

[1] 44829666

[1] 44829666

[1] 44829616

In [20]:
njeu=merge(nje, nju, by=c("Scaffold", "Position"))
nyeu=merge(nye, nyout, by=c("Scaffold", "Position"))

In [21]:
All=merge(njeu, nyeu, by=c("Scaffold", "Position"))

In [22]:
head(All)

Scaffold     Position Major.x.x Minor.x.x Maf1_E   Maf2_NJE Maf3_E   nInd_NJE
1 AAPE02055386 57060    T         C         0.000000 0.000005 0.000000 12      
2 AAPE02055386 67758    C         T         0.067869 0.022733 0.037396 10      
3 AAPE02055386 67765    C         T         0.000000 0.000003 0.000000 11      
4 AAPE02055386 67766    G         A         0.062912 0.020990 0.038813 11      
5 AAPE02055386 67785    G         A         0.000000 0.000002 0.000000 11      
6 AAPE02055386 67795    C         T         0.255406 0.255405 0.262683 12      
  Major.y.x Minor.y.x ⋯ Maf1_E.x Maf2_NYE Maf3_E.x nInd_NYE Major.y.y Minor.y.y
1 T         C         ⋯ 0.000000 0.000006 0.000000 11       T         C        
2 C         T         ⋯ 0.000000 0.000003 0.000000 10       C         T        
3 C         T         ⋯ 0.000000 0.000004 0.000000 11       C         T        
4 G         A         ⋯ 0.000000 0.000003 0.000000 10       G         A        
5 G         A         ⋯ 0.000000 0.000004 0.000000 11       G         A        
6 C         T         ⋯ 0.205502 0.205351 0.204537 11       C         T        
  Maf1_E.y Maf2_NYU Maf3_E.y nInd_NYU
1 0.000000 0.000004 0.000000 11      
2 0.050943 0.050939 0.070570 17      
3 0.044411 0.043807 0.047482 17      
4 0.043565 0.014793 0.046712 17      
5 0.000000 0.000005 0.000000 16      
6 0.226039 0.226041 0.234251 16

Making dataframes for mafs and coverage, NJ then ny, alternating pre and post. 

In [55]:
mafs=cbind(All$Maf2_NJU, All$Maf2_NJE, All$Maf2_NYU, All$Maf2_NYE)

In [56]:
head(mafs)

[,1]     [,2]     [,3]     [,4]    
[1,] 0.032491 0.000005 0.000004 0.000006
[2,] 0.033446 0.022733 0.050939 0.000003
[3,] 0.000002 0.000003 0.043807 0.000004
[4,] 0.000002 0.020990 0.014793 0.000003
[5,] 0.033610 0.000002 0.000005 0.000004
[6,] 0.092649 0.255405 0.226041 0.205351

In [57]:
covMat=cbind(All$nInd_NJU, All$nInd_NJE, All$nInd_NYU, All$nInd_NYE)

In [58]:
head(covMat)

[,1] [,2] [,3] [,4]
[1,] 9    12   11   11  
[2,] 7    10   17   10  
[3,] 6    11   17   11  
[4,] 7    11   17   10  
[5,] 7    11   16   11  
[6,] 7    12   16   11

Run CMH test with Ne used for other values, 2 generations, 2 replicates. 

In [59]:
Ne=c(296, 424)
repl=c(1,2)
tp=c(0,2)
pvals=adapted.cmh.test(freq=mafs, coverage=covMat, Ne=Ne, gen=tp, repl=repl)

#pval <- adapted.cmh.test(freq=afMat, coverage=covMat, Ne=rep(Ne,length(rep)), gen=tp, repl = rep)

Warning message in adapted.cmh.test(freq = mafs, coverage = covMat, Ne = Ne, gen = tp, :
“Ne value(s) which are not integer are converted to integer”Warning message in adapted.cmh.test(freq = mafs, coverage = covMat, Ne = Ne, gen = tp, :
“The counts assuming values 0 or equal the coverage of the considered 
                    locus are changed to 1 and to coverage-1 respectively.”Warning message in adapted.cmh.test(freq = mafs, coverage = covMat, Ne = Ne, gen = tp, :
“The counts assuming values 0 or equal the coverage of the considered 
                    locus are changed to 1 and to coverage-1 respectively.”

In [78]:
head(pvals)

[1] 0.6433869 0.5324160 0.5138580 0.9906708 0.6705819 0.6447347

In [79]:
pvalsCMH=as.data.frame(cbind(All$Scaffold, All$Position, pvals))

In [80]:
colnames(pvalsCMH)=c("Scaffold", "Position", "pvals")

In [82]:
head(pvalsCMH)

Scaffold     Position pvals            
1 AAPE02055386 57060    0.643386940890196
2 AAPE02055386 67758    0.532416047196074
3 AAPE02055386 67765    0.513858005233216
4 AAPE02055386 67766    0.990670813102399
5 AAPE02055386 67785    0.670581852460727
6 AAPE02055386 67795    0.644734663276119

In [84]:
pvalsCMH$pvals=as.numeric(as.character(pvalsCMH$pvals))

benjamini-hochberg for significance

In [88]:
pvalsCMH$rank=1:NROW(pvalsCMH)
pvalsCMH$padjBH=(pvalsCMH$rank/44829537)*.2
pvalsCMH_sig=pvalsCMH[pvalsCMH$pvals<pvalsCMH$padjBH,]
NROW(pvalsCMH_sig)

[1] 3946057

In [89]:
pvalsCMH$rank=1:NROW(pvalsCMH)
pvalsCMH$padjBH=(pvalsCMH$rank/44829537)*.1
pvalsCMH_sig=pvalsCMH[pvalsCMH$pvals<pvalsCMH$padjBH,]
NROW(pvalsCMH_sig)

[1] 2031265

Copied from the vignette, accounting for drift 

In [35]:
#simulate the starting allele frequencies 
rep <- c(1,2,3)
p <- matrix(c(round(runif(10000, min=0, max=1)*2*Ne)/(2*Ne),
              round(runif(10000, min=0, max=1)*2*Ne)/(2*Ne),
              round(runif(10000, min=0, max=1)*2*Ne)/(2*Ne)), 
              ncol=length(rep))

#simulate random drift with generations 0 and 60
Ne <- 300
tp <- c(0, 60)
p_ev1 <- wf.traj(p0=p[,1], Ne=Ne, t=tp)
p_ev2 <- wf.traj(p0=p[,2], Ne=Ne, t=tp)
p_ev3 <- wf.traj(p0=p[,3], Ne=Ne, t=tp)
afMat <- cbind(p_ev1, p_ev2, p_ev3)

#simulate the coverage matrix
covMat <- cbind(rpois(length(p), lambda=80), rpois(length(p), lambda=80), 
                rpois(length(p), lambda=80), rpois(length(p), lambda=80), 
                rpois(length(p), lambda=80), rpois(length(p), lambda=80))

#add sampling noise to the allele frequency matrix
afMat <- rbinom(n=length(covMat), size=covMat, prob=afMat) / covMat

#compute the appropriate CMH test for this situation: drift (i.e. 
#evolving population for 60 generations) and no pool sequencing 
#(i.e. poolSize = NULL)
pval <- adapted.cmh.test(freq=afMat, coverage=covMat, Ne=rep(Ne,
                                length(rep)), gen=tp, repl = rep)

Warning message in adapted.cmh.test(freq = afMat, coverage = covMat, Ne = rep(Ne, :
“Ne value(s) which are not integer are converted to integer”Warning message in adapted.cmh.test(freq = afMat, coverage = covMat, Ne = rep(Ne, :
“The counts assuming values 0 or equal the coverage of the considered 
                    locus are changed to 1 and to coverage-1 respectively.”Warning message in adapted.cmh.test(freq = afMat, coverage = covMat, Ne = rep(Ne, :
“The counts assuming values 0 or equal the coverage of the considered 
                    locus are changed to 1 and to coverage-1 respectively.”

In [36]:
head(afMat)

[,1]       [,2]      [,3]      [,4]      [,5]       [,6]     
[1,] 0.87654321 0.7638889 0.8571429 0.7848101 0.91935484 0.8518519
[2,] 0.65853659 0.4791667 0.6627907 0.5064935 0.69135802 0.5512821
[3,] 0.98780488 1.0000000 0.9857143 1.0000000 0.97260274 1.0000000
[4,] 0.01333333 0.4512195 0.0000000 0.4166667 0.01149425 0.5555556
[5,] 0.63529412 0.7294118 0.5698925 0.6700000 0.55670103 0.6593407
[6,] 0.48958333 0.2873563 0.4534884 0.3333333 0.49367089 0.3246753

In [37]:
head(tp)

[1]  0 60